name: Generate Matrix

on:
  workflow_call:
    inputs:
      semvers:
        required: true
        type: string
      oss:
        required: true
        type: string
      previousMinors:
        required: false
        type: number
        default: 3
    outputs:
      matrix:
        description: "The generated matrix"
        value: ${{ jobs.generate_matrix.outputs.matrix }}

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix-step.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Matrix
        id: generate-matrix-step
        run: |
          MATRIX=$(node .github/scripts/generate-matrix.js --semvers='${{ inputs.semvers }}' --oss='${{ inputs.oss }}' --previousMinors='${{ inputs.previousMinors }}')
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
