name: Docker Image Main Build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

env:
  pg_tle_version: '1.4.0'

jobs:
  generate_matrix_debian:
    uses: ./.github/workflows/generate-matrix.yml
    with:
      semvers: ${{ vars.LATEST_POSTGRES_VERSIONS }}
      oss: ${{ vars.OS_VERSIONS_DEBIAN }}
      output_file: matrix-debian.json

  build_debian:
    needs: generate_matrix_debian
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate_matrix_debian.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and Push Docker Image - PostgreSQL ${{ matrix.postgres_version }} - Debian ${{ matrix.os_version }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: debian/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: alvadorncorp/postgres-pg_tle:${{ matrix.postgres_version }}-${{ matrix.os_version }}.{{ env.pg_tle_version }}
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres_version }}
            POSTGRES_MAJOR=${{ matrix.postgres_major }}
            DEBIAN_VERSION=${{ matrix.os_version }}
            PG_TLE_VERSION=${{ env.pg_tle_version }}

  generate_matrix_alpine:
    uses: ./.github/workflows/generate-matrix.yml
    with:
      semvers: ${{ vars.LATEST_POSTGRES_VERSIONS }}
      oss: ${{ vars.OS_VERSIONS_ALPINE }}
      output_file: matrix-alpine.json

  build_alpine:
    needs: generate_matrix_alpine
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate_matrix_alpine.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and Push Docker Image - PostgreSQL ${{ matrix.postgres_version }} - Alpine ${{ matrix.os_version }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: alvadorncorp/postgres-pg_tle:${{ matrix.postgres_version }}-alpine${{ matrix.os_version }}.${{ env.pg_tle_version }}
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres_version }}
            POSTGRES_MAJOR=${{ matrix.postgres_major }}
            ALPINE_VERSION=${{ matrix.os_version }}
            PG_TLE_VERSION=${{ env.pg_tle_version }}
